name: MQTT.js Tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Debug Filter'     
        required: true
        default: 'mqttjs*'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Node Tests
      run: npm run test:node
      env:
        CI: true
        DEBUG: "mqttjs"
    - name: Test Typescript
      run: npm run test:typescript
      env:
        CI: true
        DEBUG: "mqttjs"

